steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/msingh243/test"]
    env: ["PROJECT_ROOT=github.com/msingh243/test"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/test-migration-1-237711/test:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/test-migration-1-237711/test:$REVISION_ID"
